[package]
name = "tls-api-openssl"
version = "0.1.3"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
description = "TLS API implementation over openssl crate"
license = "MIT/Apache-2.0"

[dependencies]
openssl = "0.*"
tls-api = { version = "0.1.3", path = "../api" }
